#!/bin/sh

# BAECKEND ESLINT CHECK
###########################
STAGED_FILES=($(git diff --diff-filter=d --cached --name-only ./js | grep -E '^.*src\/.*\.(js|jsx|tsx|ts)$'))

echo $STAGED_FILES
STAGED_FILES=$STAGED_FILES

for i in "${!STAGED_FILES[@]}"; do
  DATA=${STAGED_FILES[$i]}
  pattern="js/"
  DATA=${DATA/$pattern/}
  STAGED_FILES[$i]=$DATA
done

#npm run lint --prefix ./js -- "${STAGED_FILES[@]}" --fix
npm run lint --prefix ./js -- "${STAGED_FILES[@]}" 

ESLINT_EXIT="$?"

# Re-add files since they may have been fixed
git add "${STAGED_FILES[@]}"

if [[ "${ESLINT_EXIT}" == 0 ]]; then
  echo ""
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi